### ISSUE TITLE
sel4-tutorials building error,  CMake Error: The source directory "xxxxx/projects/sel4-tutorials/settings.cmake" is a file, not a directory.

### ISSUE THREAD

**Issue by celestialtao** [SEL4PROJ/sel4-tutorials#70]

**Comment by celestialtao** [comment]
the issue I met is like this:

Tao@Bionic:~/workspace/sel4-tutorials-manifest/develop$ ./init  --tut fault-handlers
loading initial cache file ../projects/sel4-tutorials/settings.cmake
-- Found capdl: /home/tao/workspace/sel4-tutorials-manifest/develop/projects/capdl  
-- Found camkes-tool: /home/tao/workspace/sel4-tutorials-manifest/develop/projects/sel4-tutorials  
CMake Error: The source directory "/home/tao/workspace/sel4-tutorials-manifest/develop/projects/sel4-tutorials/settings.cmake" is a file, not a directory.
Specify --help for usage, or press the help button on the CMake GUI.
Traceback (most recent call last):
  File "./init", line 90, in <module>
  File "./init", line 79, in main
  File "/home/tao/workspace/sel4-tutorials-manifest/develop/projects/sel4-tutorials/common.py", line 101, in init_directories
    return _init_build_directory(config, initialised, build_directory, tute_directory, output, config_dict=config_dict)
  File "/home/tao/workspace/sel4-tutorials-manifest/develop/projects/sel4-tutorials/common.py", line 69, in _init_build_directory
    return sh.cmake(args + [tute_directory], _cwd=directory, _out=output, _err=output)
  File "/home/tao/.local/lib/python3.6/site-packages/sh.py", line 1566, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/home/tao/.local/lib/python3.6/site-packages/sh.py", line 822, in __init__
    self.wait()
  File "/home/tao/.local/lib/python3.6/site-packages/sh.py", line 879, in wait
    self.handle_command_exit_code(exit_code)
  File "/home/tao/.local/lib/python3.6/site-packages/sh.py", line 905, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_1: 

  RAN: /usr/bin/cmake -G Ninja -DTUT_BOARD=pc -DTUT_ARCH=x86_64 -DTUTORIAL_DIR=fault-handlers -C ../projects/sel4-tutorials/settings.cmake /home/tao/workspace/sel4-tutorials-manifest/develop/fault-handlers

  STDOUT:


  STDERR:

**Comment by celestialtao** [comment]
This issue could solved by upgrading  my cmake version  from 3.13.0 to 3.21.3.
